### ISSUE TITLE
No 'Data restored completed' event

### ISSUE THREAD

**Issue by stuartlewis** [DataVault/datavault#116]
There is no 'Data restored completed' event, only a data restore started event recorded.

**Comment by tomhigginsuom** [comment]
I suspect this was because the test VM had run out of disk space (we need to add some additional checks before we carry out any copy).

**Comment by stuartlewis** [comment]
OK - thanks.  I thought I saw this on my laptop too, but will check.  Although I see the code definitely sends that event when it completes.

**Comment by stuartlewis** [comment]
Apologies - it's working ok on my version too. Closing.
