### ISSUE TITLE
Hibernate warning: HHH000139: Illegal use of @Table in a subclass of a SINGLE_TABLE hierarchy

### ISSUE THREAD

**Issue by stuartlewis** [DataVault/datavault#123]
Warning during tomcat startup:

WARN : org.hibernate.cfg.AnnotationBinder - HHH000139: Illegal use of @Table in a subclass of a SINGLE_TABLE hierarchy: org.datavaultplatform.common.event.Error
WARN : org.hibernate.cfg.AnnotationBinder - HHH000139: Illegal use of @Table in a subclass of a SINGLE_TABLE hierarchy: org.datavaultplatform.common.event.InitStates
WARN : org.hibernate.cfg.AnnotationBinder - HHH000139: Illegal use of @Table in a subclass of a SINGLE_TABLE hierarchy: org.datavaultplatform.common.event.UpdateState
WARN : org.hibernate.cfg.AnnotationBinder - HHH000139: Illegal use of @Table in a subclass of a SINGLE_TABLE hierarchy: org.datavaultplatform.common.event.deposit.Complete
WARN : org.hibernate.cfg.AnnotationBinder - HHH000139: Illegal use of @Table in a subclass of a SINGLE_TABLE hierarchy: org.datavaultplatform.common.event.deposit.ComputedSize
WARN : org.hibernate.cfg.AnnotationBinder - HHH000139: Illegal use of @Table in a subclass of a SINGLE_TABLE hierarchy: org.datavaultplatform.common.event.deposit.PackageComplete
WARN : org.hibernate.cfg.AnnotationBinder - HHH000139: Illegal use of @Table in a subclass of a SINGLE_TABLE hierarchy: org.datavaultplatform.common.event.deposit.Start
WARN : org.hibernate.cfg.AnnotationBinder - HHH000139: Illegal use of @Table in a subclass of a SINGLE_TABLE hierarchy: org.datavaultplatform.common.event.deposit.TransferComplete

**Comment by stuartlewis** [comment]
Fixed

**Comment by vetrivel-muthusamy** [comment]
@stuartlewis - Can you share how you have fixed this issue, please?

**Comment by OzkanInonlu** [comment]
yes can you tell it, I have the same issue

**Comment by burakkarasu** [comment]
@stuartlewis 
![image](https://user-images.githubusercontent.com/8415716/156383852-ec45eb25-2a52-4552-9d4b-149e7b3dc68c.png)

**Comment by stuartlewis** [comment]
@burakkarasu - you can see the commit that fixed this at https://github.com/DataVault/datavault/commit/751e0a611586bcb54eabd6cf1b10de372d3d63fa
