### ISSUE TITLE
Create custom/branded 404 and 500 error pages

### ISSUE THREAD

**Issue by stuartlewis** [DataVault/datavault#124]
Crete custom/branded 404 and 500 error pages

**Comment by stuartlewis** [comment]
First draft submitted as pull request.  However status code not correctly sent to browser, and no exception trace sent for 500s.

**Comment by tomhigginsuom** [comment]
"Are we using servlet 2.5 or 3.0? With 3.0 the error code is not needed, and means we don't need multiple entries for 404, 500, etc."

I believe the XML config files are currently set up to use servlet 2.4 (so I was seeing an XML schema error):

<web-app version="2.4"
         xmlns="http://java.sun.com/xml/ns/j2ee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee
	http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd">

We might want to upgrade to 3.0 if we want to take advantage of newer features.

**Comment by stuartlewis** [comment]
I'm not sure there's much point right now - we probably only need to throw 404s and 500s, as any other underlying HTTP codes that perhaps the broker might throw (e.g. 415 (Unsupported Media Type) or 406 (Not Acceptable)) would then get converted to a friendly error message by the webapp (and a 200 OK).

I'll try and finish off the work to get the stack trace shown over the weekend.

Do you think we should also send an email to the sys admin when a 500 occurs?  It should definitely get logged anyway.

**Comment by stuartlewis** [comment]
Fixed with latest pull request
