### ISSUE TITLE
Relative URLs on admin pages can fail

### ISSUE THREAD

**Issue by tomhigginsuom** [DataVault/datavault#131]
Currently the URLs on the admin pages are relative e.g. "users" and this works if you access the admin page via "datavault-webapp/admin/", resolving to "datavault-webapp/admin/users".

However, if you access the page without a trailing slash "datavault-webapp/admin" the link resolves to "datavault-webapp/users" which doesn't exist.

On the other pages we're constructing URLs in freemarker by using springMacroRequestContext.getContextPath(). This is a bit more verbose but allows the URLs to be a bit more flexible. Is this the right approach?

**Comment by stuartlewis** [comment]
I'll fix these.
