### ISSUE TITLE
Administration search interface - error on searching for values including '/' or '\'

### ISSUE THREAD

**Issue by tomhigginsuom** [DataVault/datavault#158]
The search interface under the administration interface (for Vaults/Deposits) throws an error on searching for values including '/' or '\' (e.g. the broker appears to interpret this as a path under a vault called 'search' due to the request mapping). Query parameters could be passed as a query string rather than as part of the base URL.

**Comment by stuartlewis** [comment]
Updated to use, for example, /vaults/search?query=foobar

    @RequestMapping(value = "/vaults/search", method = RequestMethod.GET)
    public List<Vault> searchAllVaults(@RequestHeader(value = "X-UserID", required = true) String userID,
                                       @RequestParam String query) throws Exception {

        return vaultsService.search(query);
    }

(Expect a pull request later tonight)
