### ISSUE TITLE
File format identification - Apache Tika?

### ISSUE THREAD

**Issue by tomhigginsuom** [DataVault/datavault#159]
Should we investigate file format identification using Apache Tika (or similar) as part of the ingest process? This would give some context to the deposited data which we could use for analytics/display/search.

https://tika.apache.org

**Comment by stuartlewis** [comment]
I think tika only tends to do MIME type identification (https://tika.apache.org/1.10/detection.html).  Maybe try JHOVE too or instead?

**Comment by stuartlewis** [comment]
Completed
