### ISSUE TITLE
Ability to retrieve files stored in a vault/deposit

### ISSUE THREAD

**Issue by tomhigginsuom** [DataVault/datavault#26]
The API, web front end worker need to be extended to allow files to be retrieved from the archive directory.

The worker needs to be able to operate on different job types (currently it assumes every job is a "deposit" - perhaps a container object with a "job" and a  "payload" could be used).

**Comment by seesmith** [comment]
@tomhigginsuom is this still the case?

**Comment by tomhigginsuom** [comment]
This is an old issues from the original implementation - it certainly is possible to retrieve files.
