### ISSUE TITLE
Storage: investigate plugin for Tivoli Storage Manager

### ISSUE THREAD

**Issue by dspeed2** [DataVault/datavault#395]

**Comment by robintaylor** [comment]
In case its of any interest, I once started this but gave up almost straight away. This is as far as I got... https://github.com/robintaylor/datavault/blob/tsm/datavault-common/src/main/java/org/datavaultplatform/common/storage/impl/TivoliStorageManager.java

**Comment by dspeed2** [comment]
I can see from Robin's early version that we are hoping to use this command

https://www.ibm.com/support/knowledgecenter/en/POWER8/p8hcg/p8hcg_dsmc.htm

I'll do a bit of reading and maybe try and find out if it is installed on our machines or what needs done to get it installed.

I have made a local branch for this and lifted all of Robin's code to make a TivoliStorageManager class.  I'll keep using this branch as things progress.

**Comment by dspeed2** [comment]
I haven't done much on DV since Friday Robin has sent us more info via Slack / Email I'm just pasting it here so it doesn't get lost.  I will be reading / responding to it this afternoon.

Via Slack

Hi all, yes I *think* dsmc is the way to go, although I didn't get far enough to be 100% sure. Unfortunately it will be tricky to test. You need some client software installed, but there is also a central TSM server somewhere that needs to know about the machine with the client software. This is all configured by the Unix guys and the existing DV test machine does have the client software on it, although I never got as far as testing it. There was a Unidesk call for this stuff so I'll dig it out for reference. If you want more info or a chat about this just let me know. Cheers.


[4:43] 
Have a look at "I170807-0327 Install TSM Client on lac-vault-test1.is.ed.ac.uk"

Via Email

Hi all,

Just thought I would scribble down everything I know about this...

The idea is DV will write two copies of an archive to the two tape servers hosted by the Research Services team, Kevin Tomlinson being the main contact point there. It was he who first pointed me to the 'dsmc' command.

The first thing is that the central TSM server needs to be aware of the client that will be initiating the archive. I think Kev will be reluctant to allow us to test on a local machines so it may mean having to do all testing from our test and then live servers. Those servers also need  client software installed on them. As an added complication those servers are not provided by Research Services but by Martin Campbell's Enterprise Services team. They also have their own TSM server, but we are not using that. This means there will be a certain amount of running between the two Unix teams trying to get things working. In fact our test server should now have the TSM client installed and be configured to write to one of the Research Services TSM servers. I got as far as requesting that but never tested it (see Unidesk call "I170807-0327 Install TSM Client on lac-vault-test1.is.ed.ac.uk").

The next step should probably be to test that setup manually by checking the config and then trying a dsmc command from the command line. In fact we can probably test much of this from the command line so the fact that we can't do it on our local machines needn't be too much of a hindrance. Once it has all been tested then it should hopefully just be a case of sticking the tested commands into the program code. There are some unknowns here though.

I suspect the dsmc command may just send a message to the TSM server saying "please come and archive fileA", so how do we monitor the process and know when it completes successfully? It may be that dsmc will return immediately effectively saying "I have sent the request successfully!", but we need to know that the archive completes successfully. Is there another command we can send to monitor progress? Do we also need to know and store the Id of the tape archive? Or can we supply that with the command? It should be possible to test all this stuff at the command line though. Kevin may be reluctant to involve himself with this project but he is the main man for this stuff, so just pester him.

The next complication is that we are supposed to write two copies to two different servers. This is complicated because the client is normally configured to talk to a particular server. I don't think this can be overridden on the command line so it may mean writing one copy, then editing the config, then writing the second copy. I think there may be client commands that allow editing of the config without having to hack the config files directly. Kevin said this would be "no problem" :) . I would suggest that we forget about the second copy to begin with and try and get it working with just the one copy. At that point the code could be contributed as a plugin. The later stuff about the second copy is probably only of interest to Edinburgh so shouldn't go into the Open Source code. 

I think thats all, good luck!

**Comment by dspeed2** [comment]
The direct unidesk link to the tickets to install dsmc on our test machine is here https://ed.unidesk.ac.uk/tas/secure/mango/window/3?t=1511275564201

**Comment by dspeed2** [comment]
Do we log onto lac-vault-test1.is.ed.ac.uk via a password or do I need to send my public key somewhere?

**Comment by dspeed2** [comment]
I've managed to log on as lacddt@lac-vault-test1

[lacddt@lac-vault-test1]$ dsmc -query access
ANS0102W Unable to open the message repository /opt/tivoli/tsm/client/ba/bin/EN_GB/dsmclientV3.cat. The American English repository will be used instead.
ANS1398E Initialization functions cannot open one of the Tivoli Storage Manager logs or a related file: /opt/tivoli/tsm/client/ba/bin/dsmerror.log. errno = 13, Permission denied

Presumably either I'm using the wrong user or something needs configured.

**Comment by dspeed2** [comment]
Help page about the error messages

https://www.ibm.com/support/knowledgecenter/en/SSGSG7_6.2.0/com.ibm.itsm.msgs.client.doc/msgs_client971.html

**Comment by dspeed2** [comment]
One thing I did notice is that if you actually look at the log file it is complaining about not having permission for it contains warnings about not being able to start properly.

The timestamp on the file matches the uptime of the machine so it looks like it might not have restarted properly after a reboot on the 1st Nov.
